import type {Metadata} from 'next'
import './globals.css'
import {ReactNode} from "react";
import {GeistSans} from 'geist/font/sans'


export const metadata: Metadata = {
    title: 'Fikiri | home',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className={`${GeistSans.className} overflow-x-hidden`}>{children}</body>
        </html>
    )
}
