import type {Metadata} from 'next'
import './globals.css'
import {ReactNode} from "react";
import {Roboto} from 'next/font/google'


const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin-ext'],
})

export const metadata: Metadata = {
    title: 'Fikiri | home',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className={`${roboto.className} text-neutral-50`}>{children}</body>
        </html>
    )
}
